server:
  port: 9000
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 让gateway可以发现nacos中的微服务
      routes:
        - id: uaa_route
          uri: lb://uaa-service # lb指的是从nacos中按照名称获取微服务,并遵循负载均 衡策略
          predicates:
            - Path=/uaa/**
          filters:
            - StripPrefix=1
        - id: product_route
          uri: lb://product-service 
          predicates:
            - Path=/product/**
          filters:
            - StripPrefix=1
        - id: seckill_route
          uri: lb://seckill-service 
          predicates:
            - Path=/seckill/**
          filters:
            - StripPrefix=1
        - id: ws_route
          uri: lb://websocket-service 
          predicates:
            - Path=/ws/**
          filters:
            - StripPrefix=1

