server:
  port: 8041
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shop-product?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    driverClassName: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: admin
    maxActive: 1000
    initialSize: 100
    maxWait: 60000
    minIdle: 500
mybatis:
  configuration:
    default-fetch-size: 100
    default-statement-timeout: 3000
    map-underscore-to-camel-case: true
  mapperLocations: classpath:cn/wolfcode/mapper/*Mapper.xml
ribbon:
  eager-load:
    enabled: true