server:
  port: 8061
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shop-seckill?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    driverClassName: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: admin
    maxActive: 1000
    initialSize: 100
    maxWait: 60000
    minIdle: 500
mybatis:
  configuration:
    default-fetch-size: 100
    default-statement-timeout: 3000
    map-underscore-to-camel-case: true
  mapperLocations: classpath:cn/wolfcode/mapper/*Mapper.xml
ribbon:
  eager-load:
    enabled: true
  ReadTimeout: 10000            
  ConnectTimeout: 10000          
  MaxAutoRetries: 0             
  MaxAutoRetriesNextServer: 0  
rocketmq:
  producer:
    group: seckill-group

pay:
  returnUrl: http://8sesy6.natappfree.cc/seckill/orderPay/return_url
  notifyUrl: http://8sesy6.natappfree.cc/seckill/orderPay/notify_url
  frontEndPayUrl: http://localhost/order_detail.html?orderNo=
  errorUrl: http://localhost/50x.html